//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public string Symptom { get; set; }
        public string Industry_name { get; set; }
        public string Disease_name { get; set; }
    }
}
