
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace FIT5120App.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OLD
{

    public string Disease_Name { get; set; }

    public string Disease_Description { get; set; }

}

}
